import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Forte - Distribuidora de Móveis",
  icons: { icon: "/favicon.ico" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
