import type { Metadata } from "next";

import "./globals.css";
import { Menu } from "@/src/components/Menu";
import { Container } from "@/src/components/Container";
import { Footer } from "@/src/components/Footer";

export const metadata: Metadata = {
  title: "Forte - Distribuidora de Móveis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
      </head>
      <body>
        <Container>
          <Menu />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
