import type { Metadata } from "next";

import "./globals.css";
import { Menu } from "@/src/components/Menu";
import { Container } from "@/src/components/Container";
import { Footer } from "@/src/components/Footer";
import { WhatsAppButton } from "@/src/components/WhatsAppButton";

export const metadata: Metadata = {
  title: "Forte - Distribuidora de Móveis",
  icons: {
    icon: '/favicon.ico'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
      </head>
      <body>
        <Container>
          <Menu />
          {children}
          <Footer />
        </Container>
          <WhatsAppButton 
          size={40} 
          classes="p-2 fixed bottom-4 right-4 md:right-11 md:bottom-11" 
          message="Olá! Vi o site da loja e gostaria de mais informações."/>
      </body>
    </html>
  );
}
